version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api-db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data